services:
    postgres-db:
      image: postgres
      container_name: mmg_critic_db
      environment:
        POSTGRES_DB: mmg_critic_db
        POSTGRES_HOST_AUTH_METHOD: trust
        POSTGRES_PASSWORD: password

      volumes:
        - ./init-db:/docker-entrypoint-initdb.d
      ports:
        - "5432:5432"
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres -d mmg_critic_db" ]
        interval: 30s
        timeout: 10s
        retries: 5
#    redis:
#      image: redis
#      expose:
#          - "6379"
#      container_name: redis
#      environment:
#          REDIS_HOST_AUTH_METHOD: trust
#          ALLOW_EMPTY_PASSWORD: "yes"
#      ports:
#          - "6379:6379"
#      healthcheck:
#          test: [ "CMD", "redis-cli", "ping" ]
#          interval: 30s
#          timeout: 10s
#          retries: 5


